name: Build, Scan and Publish

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CACHE_IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cloud-tech-cache:cache-main

jobs:
  build-scan-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # QEMU dla arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logowanie DockerHub (cache)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Logowanie GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Nazwy tagów
      - name: Prepare image tags
        id: prep
        run: |
          IMAGE=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "sha_tag=sha-${GITHUB_SHA}" >> $GITHUB_OUTPUT

      # Budowa obrazu do skanowania
      # (bez push do GHCR)
      - name: Build image for security scan
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: local-scan-image:latest
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max

      # Instalacja Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/

      # Test CVE
      # Job zatrzyma się przy HIGH lub CRITICAL
      - name: Scan image with Trivy
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            local-scan-image:latest

      # Dopiero po przejściu testu bezpieczeństwa:
      # budowa multiarch + push do GHCR
      - name: Build and push multi-platform image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true

          tags: |
            ${{ steps.prep.outputs.image }}:latest
            ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.sha_tag }}

          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max